---
- name: Ensure php.ini configuration is in place
  template:
    src: 'php.ini.j2'
    dest: '{{ php_ini_path }}'
    owner: 'root'
    group: 'root'
  notify:
    - Reload php-fpm
    - Restart apache2

- name: Ensure OpCache configuration is in place
  template:
    src: 'opcache.ini.j2'
    dest: '{{ php_extension_conf_path }}/{{ php_opcache_conf_filename }}'
    owner: 'root'
    group: 'root'
  when: php_opcache_enable
  notify:
    - Reload php-fpm
    - Restart apache2

- name: Ensure php-fpm configuration is in place
  template:
    src: 'php-fpm.conf.j2'
    dest: '{{ __php_fpm_conf_path }}'
    owner: 'root'
    group: 'root'
  when: php_manage_fpm == True and php_install_type == 'fpm'
  notify: Reload php-fpm

- name: Find configured fpm pools
  shell: ls -1 {{ php_fpm_pools_path }}
  register: configured_pools
  changed_when: False
  when: php_manage_fpm == True and php_fpm_pools_remove_unmanaged == True and php_install_type == 'fpm'
  tags: skip_ansible_lint

- name: Remove unmanaged fpm pool configurations
  file:
    name: '{{ php_fpm_pools_path }}/{{ item }}'
    state: absent
  with_items: '{{ configured_pools.stdout_lines }}'
  when: php_manage_fpm == True and php_fpm_pools_remove_unmanaged == True and php_install_type == 'fpm' and item[:-5] not in php_fpm_pools.keys()
  notify: Reload php-fpm

- name: Ensure php-fpm pools are configured
  template:
    src: 'fpm-pool.conf.j2'
    dest: '{{ php_fpm_pools_path }}/{{ item.key }}.conf'
    owner: 'root'
    group: 'root'
  with_dict: '{{ php_fpm_pools }}'
  no_log: True
  when: php_manage_fpm == True and php_install_type == 'fpm'
  notify: Reload php-fpm

- name: Ensure rsync package is installed to synchronize configuration | Debian
  apt:
    pkg: 'rsync'
  when: ansible_os_family == 'Debian' and php_sync_environment_config == True

- name: Synchronize configurations (cli, fpm & apache2 environments will have the same configuration) | Debian
  shell: 'rsync -avh --delete {{ php_conf_path }}/ {{ __php_conf_base }}/{{ item }}/'
  always_run: yes
  changed_when: False
  with_items: '{{ php_install_types_filtered }}'
  when: ansible_os_family == 'Debian' and php_sync_environment_config == True
  tags: skip_ansible_lint
