---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Ensure PHP packages are installed | Debian
  package:
    name: "{{ php_packages }}"
    state: present
  notify:
    - Reload php-fpm
    - Restart apache2
