---
- name: Ensure PHP packages are installed | Redhat
  package:
    name: "{{ php_packages }}"
    state: present
  with_items: '{{ php_packages }}'
  notify:
    - Reload php-fpm
    - Restart apache2