---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
  options:
    config-file: ../../../resources/.yamllint
platforms:
    - name: debian8
      image: jgeusebroek/debian8-molecule
      image_version: latest
      privileged: true
      command: /lib/systemd/systemd
      volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      groups:
        - debian
    - name: centos7
      image: jgeusebroek/centos7-molecule
      image_version: latest
      privileged: true
      command: /usr/lib/systemd/systemd
      volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      groups:
        - redhat
    - name: ubuntu1604
      image: jgeusebroek/ubuntu1604-molecule
      image_version: latest
      privileged: true
      command: /lib/systemd/systemd
      volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      groups:
        - ubuntu
    # - name: ubuntu1404
    #   image: jgeusebroek/ubuntu1404-molecule
    #   image_version: latest
    #   privileged: true
    #   command: /sbin/init
    #   groups:
    #     - ubuntu
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
