---
- hosts: all

  vars:
    php_fpm_pools:
      "www":
        listen: '0.0.0.0:9000'
        custom_settings:
          security.limit_extensions: '.php'

  roles:
    - { role: jgeusebroek.php, php_packages: [ "php7.4-cli", "php7.4-fpm", "php7.4-opcache" ], php_sync_environment_config: true, when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' }
    - { role: jgeusebroek.php, php_packages: [ "php72w-cli", "php72w-fpm", "php72w-opcache" ], when: ansible_distribution == 'CentOS' and ansible_distribution_major_version < '8'}
    - { role: jgeusebroek.php, php_packages: [ "php-cli", "php-fpm", "php-opcache" ], when: ansible_distribution == 'CentOS' and ansible_distribution_major_version > '7'}
