---
- hosts: all

  vars:
    php_fpm_pools:
      "www":
        listen: '0.0.0.0:9000'
        custom_settings:
          security.limit_extensions: '.php'

  roles:
    - { role: jgeusebroek.php, php_packages: [ "php7.2-cli", "php7.2-fpm", "php7.2-opcache" ], php_sync_environment_config: true, when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' }
    - { role: jgeusebroek.php, php_packages: [ "php71w-cli", "php71w-fpm", "php71w-opcache" ], when: ansible_distribution == 'CentOS' }
